### ISSUE TITLE
功能异常 缺失

### ISSUE THREAD

**Issue by Smile8848** [vixalie/comic_viewer#2]
![QQ图片20230318160408](https://user-images.githubusercontent.com/31927778/226093644-2ba4668f-a3c1-4d4a-a19c-14e1c17a118e.png)
![截屏 2023-03-18 16 01 27](https://user-images.githubusercontent.com/31927778/226093660-3feae009-d701-4f1b-ae8a-ba72a119f3e9.jpg)
有的文件夹都无法打开 然后显示比例似乎不能调整 调整中间就一大块空白

**Comment by vixalie** [comment]
试试新版吧，新版已经重构了。
